name: Detect and Alert on Package.json Changes
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  detect_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python .github/scripts/detect_package_changes.py

      - name: Comment on PR if package.json changed
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (process.env.PACKAGE_JSON_CHANGED === 'true') {
              const message = "Changes detected in package.json.";
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }
